### ISSUE TITLE
Status de Follow en boton del perfil

### ISSUE THREAD

**Issue by AngelZacarias** [AngelZacarias/smart-notes#43]
Al entar al perfil de un usuario hacer una query hacia follows para saber si ya lo sigue o no y asi desplegar la leyenda correcta en el boton de "Seguir" o "Dejar de Seguir"

**Comment by julioantonio12** [comment]
Según yo sí validé eso, pero en un rato lo vuelvo a checar

**Comment by julioantonio12** [comment]
Ya lo corregí, necesitaba hacer un refectQuery de mi query de obtener el follow en la mutación de seguir usuario.
